# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT
#
# For documentation on the format of this file, see
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "docker"
    directory: "/images"
    schedule:
      interval: "weekly"
      day: "saturday"
