# Copyright (c) eBPF for Windows contributors
# SPDX-License-Identifier: MIT
---
blank_issues_enabled: true
contact_links:
  - name: "\U00002753 Comment, Question or Problem"
    url: https://github.com/microsoft/ebpf-for-windows/discussions
    about: Please direct general discussion here.
