# Copyright (c) eBPF for Windows contributors
# SPDX-License-Identifier: MIT
---
name: Scorecards

on:
  push:
    branches: [main, 'gh-readonly-queue/main/**']
  pull_request:
    branches: [main, 'gh-readonly-queue/main/**']
  merge_group:
    branches: [main, 'gh-readonly-queue/main/**']

concurrency:
  # Cancel any Scorecards workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: scorecards-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      id-token: write
      actions: read
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e  # v2.14.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            www.bestpractices.dev:443
            github.com:443
            api.deps.dev:443
            fulcio.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            rekor.sigstore.dev:443

      - name: "Checkout code"
        if: github.ref_name == 'main'
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: "Run analysis"
        if: github.ref_name == 'main'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a  # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          # Read-only PAT token. To create it,
          # follow the steps in https://github.com/ossf/scorecard-action#pat-token-creation.
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          # Publish the results to enable scorecard badges. For more details, see
          # https://github.com/ossf/scorecard-action#publishing-results.
          # For private repositories, `publish_results` will automatically be set to `false`,
          # regardless of the value entered here.
          publish_results: ${{ github.event_name != 'pull_request' && github.event_name != 'merge_group'}}

      # Upload the results as artifacts (optional).
      - name: "Upload artifact"
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 10

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: github.ref_name == 'main'
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e
        with:
          sarif_file: results.sarif
