# Copyright (c) eBPF for Windows contributors
# SPDX-License-Identifier: MIT
---
name: Scorecards

on:
  push:
    branches: [main, 'gh-readonly-queue/main/**']
  pull_request:
    branches: [main, 'gh-readonly-queue/main/**']
  merge_group:
    branches: [main, 'gh-readonly-queue/main/**']

concurrency:
  # Cancel any Scorecards workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: scorecards-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      id-token: write
      actions: read
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0  # v2.12.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            www.bestpractices.dev:443
            github.com:443
            api.deps.dev:443

      - name: "Checkout code"
        if: github.ref_name == 'main'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: "Run analysis"
        if: github.ref_name == 'main'
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186  # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          # Read-only PAT token. To create it,
          # follow the steps in https://github.com/ossf/scorecard-action#pat-token-creation.
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          # Publish the results to enable scorecard badges. For more details, see
          # https://github.com/ossf/scorecard-action#publishing-results.
          # For private repositories, `publish_results` will automatically be set to `false`,
          # regardless of the value entered here.
          publish_results: ${{ github.event_name != 'pull_request' && github.event_name != 'merge_group'}}

      # Upload the results as artifacts (optional).
      - name: "Upload artifact"
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 10

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: github.ref_name == 'main'
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f
        with:
          sarif_file: results.sarif
